//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingMaterialsStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        private static Entities _context;
        public Entities() : base("name=Entities")
        { }
        public static Entities GetContext()
        {
            if (_context == null) _context = new Entities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories_Table> Categories_Table { get; set; }
        public virtual DbSet<OrderDetails_Table> OrderDetails_Table { get; set; }
        public virtual DbSet<Orders_Table> Orders_Table { get; set; }
        public virtual DbSet<Products_Table> Products_Table { get; set; }
        public virtual DbSet<ShoppingCarts_Table> ShoppingCarts_Table { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users_Table> Users_Table { get; set; }
    }
}
