//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingMaterialsStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails_Table
    {
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public string Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Products_Table Products_Table { get; set; }
    }
}
