//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingMaterialsStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products_Table()
        {
            this.Cart_Table = new HashSet<Cart_Table>();
            this.OrderDetails_Table = new HashSet<OrderDetails_Table>();
            this.ShoppingCarts_Table = new HashSet<ShoppingCarts_Table>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }
        public string CurrentPhoto
        {
            get
            {
                if (string.IsNullOrEmpty(ImageURL) || string.IsNullOrWhiteSpace(ImageURL))
                {
                    return "/Image/16.jpg";
                }
                else
                {
                    return "/Image/" + ImageURL;
                }
            }
        }


            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart_Table> Cart_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails_Table> OrderDetails_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCarts_Table> ShoppingCarts_Table { get; set; }
    }
}
