//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingMaterialsStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCarts_Table
    {
        public int ShoppingCartID { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public string Quantity { get; set; }
    
        public virtual Products_Table Products_Table { get; set; }
        public virtual Users_Table Users_Table { get; set; }
    }
}
